import { Task, TaskRunEnvironment, TaskRunStatus } from 'products/tasks/frontend/types'

const SIGNAL_DESCRIPTION =
    'Investigate RequestTimeTooSkewed S3 failures and turn the findings into concrete follow-up work for the product and engineering teams.'

function buildTask(index: number, props: Partial<Task>): Task {
    const taskNumber = 100 + index
    return {
        id: `task-hb-${index}`,
        task_number: taskNumber,
        slug: `HB-${taskNumber}`,
        title: `Hogbot demo task ${index}`,
        description: SIGNAL_DESCRIPTION,
        origin_product: 'hogbot' as Task['origin_product'],
        repository: 'posthog/posthog',
        github_integration: null,
        json_schema: null,
        latest_run: null,
        created_at: `2026-03-25T${String(8 + (index % 10)).padStart(2, '0')}:00:00Z`,
        updated_at: `2026-03-25T${String(8 + (index % 10)).padStart(2, '0')}:30:00Z`,
        created_by: null,
        ...props,
    }
}

export const MOCK_HOGBOT_TASKS: Task[] = [
    buildTask(1, {
        title: 'Investigate clock skew on object storage workers',
        description:
            'Trace why `RequestTimeTooSkewed` is reaching production workers and identify which hosts are drifting furthest from S3 server time.',
        latest_run: {
            id: 'run-hb-1',
            task: 'task-hb-1',
            stage: null,
            branch: null,
            status: TaskRunStatus.IN_PROGRESS,
            environment: TaskRunEnvironment.CLOUD,
            log_url: null,
            error_message: null,
            output: null,
            state: {},
            artifacts: [],
            created_at: '2026-03-25T09:00:00Z',
            updated_at: '2026-03-25T09:22:00Z',
            completed_at: null,
        },
    }),
    buildTask(2, {
        title: 'Add monitoring for NTP drift in sandbox workloads',
        description:
            'Create instrumentation and alerts for machine clock drift so HogBot can spot future skew-related incidents before requests fail.',
        latest_run: {
            id: 'run-hb-2',
            task: 'task-hb-2',
            stage: null,
            branch: null,
            status: TaskRunStatus.QUEUED,
            environment: TaskRunEnvironment.CLOUD,
            log_url: null,
            error_message: null,
            output: null,
            state: {},
            artifacts: [],
            created_at: '2026-03-25T09:10:00Z',
            updated_at: '2026-03-25T09:10:00Z',
            completed_at: null,
        },
    }),
    buildTask(3, {
        title: 'Document S3 RequestTimeTooSkewed recovery playbook',
        description:
            'Write an operator-facing incident playbook covering diagnosis steps, expected telemetry, and mitigation options for S3 clock skew errors.',
        latest_run: {
            id: 'run-hb-3',
            task: 'task-hb-3',
            stage: null,
            branch: null,
            status: TaskRunStatus.COMPLETED,
            environment: TaskRunEnvironment.CLOUD,
            log_url: null,
            error_message: null,
            output: { summary: 'Initial playbook draft created in research/' },
            state: {},
            artifacts: [],
            created_at: '2026-03-25T09:20:00Z',
            updated_at: '2026-03-25T09:48:00Z',
            completed_at: '2026-03-25T09:48:00Z',
        },
    }),
    buildTask(4, {
        title: 'Check AWS signing libraries for skew tolerance',
        description:
            'Review the object-storage call path and verify whether botocore retry and signing settings can be made more tolerant of moderate clock drift.',
        latest_run: {
            id: 'run-hb-4',
            task: 'task-hb-4',
            stage: null,
            branch: null,
            status: TaskRunStatus.NOT_STARTED,
            environment: TaskRunEnvironment.CLOUD,
            log_url: null,
            error_message: null,
            output: null,
            state: {},
            artifacts: [],
            created_at: '2026-03-25T09:30:00Z',
            updated_at: '2026-03-25T09:30:00Z',
            completed_at: null,
        },
    }),
    buildTask(5, {
        title: 'Audit object_storage.py error handling for skew failures',
        description:
            'Inspect how `posthog/storage/object_storage.py` surfaces skew-related failures and propose clearer logging or retry behavior.',
        latest_run: {
            id: 'run-hb-5',
            task: 'task-hb-5',
            stage: null,
            branch: null,
            status: TaskRunStatus.FAILED,
            environment: TaskRunEnvironment.CLOUD,
            log_url: null,
            error_message: 'Repository checkout failed while preparing reproduction environment.',
            output: null,
            state: {},
            artifacts: [],
            created_at: '2026-03-25T09:40:00Z',
            updated_at: '2026-03-25T09:51:00Z',
            completed_at: '2026-03-25T09:51:00Z',
        },
    }),
    buildTask(6, {
        title: 'Build a reproduction for skewed signed S3 requests',
        description:
            'Create a minimal local reproduction that shifts system time and confirms the exact failure path seen in production traces.',
        latest_run: {
            id: 'run-hb-6',
            task: 'task-hb-6',
            stage: null,
            branch: null,
            status: TaskRunStatus.COMPLETED,
            environment: TaskRunEnvironment.CLOUD,
            log_url: null,
            error_message: null,
            output: { summary: 'Reproduction plan drafted; waiting on controlled sandbox clock skew test.' },
            state: {},
            artifacts: [],
            created_at: '2026-03-25T09:50:00Z',
            updated_at: '2026-03-25T10:18:00Z',
            completed_at: '2026-03-25T10:18:00Z',
        },
    }),
    buildTask(7, {
        title: 'Review infra rollout for recent time-sync regressions',
        description:
            'Compare recent infrastructure changes against the first-seen timestamps of the new error-tracking issues to find likely regressions.',
        latest_run: {
            id: 'run-hb-7',
            task: 'task-hb-7',
            stage: null,
            branch: null,
            status: TaskRunStatus.CANCELLED,
            environment: TaskRunEnvironment.CLOUD,
            log_url: null,
            error_message: null,
            output: null,
            state: {},
            artifacts: [],
            created_at: '2026-03-25T10:00:00Z',
            updated_at: '2026-03-25T10:05:00Z',
            completed_at: '2026-03-25T10:05:00Z',
        },
    }),
    buildTask(8, {
        title: 'Summarize all 10 skew-related signals into one incident report',
        description:
            'Aggregate the example HogBot signals, cluster their common traits, and write an incident summary a human can review quickly.',
        latest_run: {
            id: 'run-hb-8',
            task: 'task-hb-8',
            stage: null,
            branch: null,
            status: TaskRunStatus.IN_PROGRESS,
            environment: TaskRunEnvironment.CLOUD,
            log_url: null,
            error_message: null,
            output: null,
            state: {},
            artifacts: [],
            created_at: '2026-03-25T10:10:00Z',
            updated_at: '2026-03-25T10:41:00Z',
            completed_at: null,
        },
    }),
    buildTask(9, {
        title: 'Identify customer-facing impact of skewed object reads',
        description:
            'Estimate which product surfaces fail when S3 object reads skew out of tolerance and note the highest-priority user-facing risks.',
        latest_run: {
            id: 'run-hb-9',
            task: 'task-hb-9',
            stage: null,
            branch: null,
            status: TaskRunStatus.QUEUED,
            environment: TaskRunEnvironment.CLOUD,
            log_url: null,
            error_message: null,
            output: null,
            state: {},
            artifacts: [],
            created_at: '2026-03-25T10:20:00Z',
            updated_at: '2026-03-25T10:20:00Z',
            completed_at: null,
        },
    }),
    buildTask(10, {
        title: 'Prepare code-change task for automatic clock skew remediation',
        description:
            'Define the concrete engineering task to add detection, remediation, and safer retries for clock-skew-induced S3 failures.',
        latest_run: {
            id: 'run-hb-10',
            task: 'task-hb-10',
            stage: null,
            branch: null,
            status: TaskRunStatus.COMPLETED,
            environment: TaskRunEnvironment.CLOUD,
            log_url: null,
            error_message: null,
            output: { summary: 'Follow-up implementation task drafted with acceptance criteria.' },
            state: {},
            artifacts: [],
            created_at: '2026-03-25T10:30:00Z',
            updated_at: '2026-03-25T10:55:00Z',
            completed_at: '2026-03-25T10:55:00Z',
        },
    }),
]
