import { Task, TaskRunEnvironment, TaskRunStatus } from 'products/tasks/frontend/types'

export const MOCK_HOGBOT_TASKS: Task[] = [
    {
        id: 'task-hb-1',
        task_number: 101,
        slug: 'HB-101',
        title: 'Analyze user churn patterns',
        description: 'Research and document user churn patterns across different cohorts and identify actionable insights.',
        origin_product: 'hogbot' as Task['origin_product'],
        repository: null,
        github_integration: null,
        json_schema: null,
        latest_run: {
            id: 'run-1',
            task: 'task-hb-1',
            stage: null,
            branch: null,
            status: TaskRunStatus.COMPLETED,
            environment: TaskRunEnvironment.CLOUD,
            log_url: null,
            error_message: null,
            output: { summary: 'Identified 3 key churn segments' },
            state: {},
            artifacts: [],
            created_at: '2026-03-24T10:00:00Z',
            updated_at: '2026-03-24T10:45:00Z',
            completed_at: '2026-03-24T10:45:00Z',
        },
        created_at: '2026-03-24T10:00:00Z',
        updated_at: '2026-03-24T10:45:00Z',
        created_by: null,
    },
    {
        id: 'task-hb-2',
        task_number: 102,
        slug: 'HB-102',
        title: 'Mobile retention drop investigation',
        description: 'Investigate the sudden drop in mobile user retention starting March 17.',
        origin_product: 'hogbot' as Task['origin_product'],
        repository: null,
        github_integration: null,
        json_schema: null,
        latest_run: {
            id: 'run-2',
            task: 'task-hb-2',
            stage: null,
            branch: null,
            status: TaskRunStatus.IN_PROGRESS,
            environment: TaskRunEnvironment.CLOUD,
            log_url: null,
            error_message: null,
            output: null,
            state: {},
            artifacts: [],
            created_at: '2026-03-25T10:05:00Z',
            updated_at: '2026-03-25T10:30:00Z',
            completed_at: null,
        },
        created_at: '2026-03-25T10:05:00Z',
        updated_at: '2026-03-25T10:30:00Z',
        created_by: null,
    },
    {
        id: 'task-hb-3',
        task_number: 103,
        slug: 'HB-103',
        title: 'Weekly insights summary generation',
        description: 'Generate a weekly summary of key product metrics, anomalies, and recommendations.',
        origin_product: 'hogbot' as Task['origin_product'],
        repository: null,
        github_integration: null,
        json_schema: null,
        latest_run: {
            id: 'run-3',
            task: 'task-hb-3',
            stage: null,
            branch: null,
            status: TaskRunStatus.COMPLETED,
            environment: TaskRunEnvironment.CLOUD,
            log_url: null,
            error_message: null,
            output: { summary: 'Weekly report generated' },
            state: {},
            artifacts: [],
            created_at: '2026-03-24T08:00:00Z',
            updated_at: '2026-03-24T08:15:00Z',
            completed_at: '2026-03-24T08:15:00Z',
        },
        created_at: '2026-03-24T08:00:00Z',
        updated_at: '2026-03-24T08:15:00Z',
        created_by: null,
    },
    {
        id: 'task-hb-4',
        task_number: 104,
        slug: 'HB-104',
        title: 'Feature flag performance audit',
        description: 'Audit feature flag evaluation latency and identify optimization opportunities.',
        origin_product: 'hogbot' as Task['origin_product'],
        repository: null,
        github_integration: null,
        json_schema: null,
        latest_run: {
            id: 'run-4',
            task: 'task-hb-4',
            stage: null,
            branch: null,
            status: TaskRunStatus.QUEUED,
            environment: TaskRunEnvironment.CLOUD,
            log_url: null,
            error_message: null,
            output: null,
            state: {},
            artifacts: [],
            created_at: '2026-03-25T11:00:00Z',
            updated_at: '2026-03-25T11:00:00Z',
            completed_at: null,
        },
        created_at: '2026-03-25T11:00:00Z',
        updated_at: '2026-03-25T11:00:00Z',
        created_by: null,
    },
]
