/**
 * PostHog Design System — Color Tokens (shadcn-aligned)
 *
 * Each value is [light, dark]. Index 0 = light, index 1 = dark.
 */

import { cssVarsFlat } from './css'
import { generateShadowCSS } from './shadow'
import { generateSpacingCSS } from './spacing'
import { generateFontSizeCSS, generateFontFamilyCSS } from './typography'

export const semanticColors: Record<string, ColorTuple> = {
    background: ['oklch(0.97 0.006 106)', 'hsl(240 8% 8%)', 'bg-background'],
    foreground: ['oklch(0.13 0.028 262)', 'oklch(0.967 0.003 265)', 'text-foreground'],

    card: ['oklch(1 0 0)', 'hsl(235 8% 15%)', 'bg-card'],
    'card-foreground': ['oklch(0.13 0.028 262)', 'oklch(0.967 0.003 265)', 'text-card-foreground'],

    popover: ['oklch(1 0 0)', 'hsl(235 8% 15%)', 'bg-popover'],
    'popover-foreground': ['oklch(0.13 0.028 262)', 'oklch(0.967 0.003 265)', 'text-popover-foreground'],

    primary: ['black', 'white', 'bg-primary'],
    'primary-foreground': ['oklch(1 0 0)', 'oklch(0.13 0.028 262)', 'text-primary-foreground'],

    secondary: ['oklch(0.967 0.001 286.375)', 'oklch(0.274 0.006 286.033)', 'bg-secondary'],
    'secondary-foreground': ['oklch(0.21 0.006 285.885)', 'oklch(0.985 0 0)', 'text-secondary-foreground'],

    muted: ['oklch(0.97 0.006 106)', 'hsl(240 8% 10%)', 'bg-muted'],
    'muted-foreground': ['oklch(0.446 0.03 257)', 'oklch(0.709 0 0)', 'text-muted-foreground'],

    accent: ['oklch(0.923 0.003 49)', 'hsl(230 8% 20%)', 'bg-accent'],
    'accent-foreground': ['oklch(0.13 0.028 262)', 'oklch(0.967 0.003 265)', 'text-accent-foreground'],

    destructive: ['oklch(0.577 0.245 27)', 'oklch(0.704 0.191 22)', 'bg-destructive'],
    'destructive-foreground': ['oklch(1 0 0)', 'oklch(0.13 0.028 262)', 'text-destructive-foreground'],

    success: ['oklch(0.627 0.194 149)', 'oklch(0.792 0.209 152)', 'bg-success'],
    'success-foreground': ['oklch(1 0 0)', 'oklch(0.13 0.028 262)', 'text-success-foreground'],

    warning: ['oklch(0.554 0.135 66)', 'oklch(0.852 0.199 92)', 'bg-warning'],
    'warning-foreground': ['oklch(0.13 0.028 262)', 'oklch(0.13 0.028 262)', 'text-warning-foreground'],

    info: ['oklch(0.546 0.245 263)', 'oklch(0.707 0.165 255)', 'bg-info'],
    'info-foreground': ['oklch(1 0 0)', 'oklch(0.13 0.028 262)', 'text-info-foreground'],

    border: ['oklch(0.923 0.003 49)', 'hsl(230 8% 20%)', 'border-border'],
    input: ['oklch(0.923 0.003 49)', 'hsl(230 8% 20%)', 'border-input'],
    ring: ['hsl(228 100% 56%)', 'oklch(0.707 0.165 255)', 'border-ring'],
} as const

// ── Types ──────────────────────────────────────────────

export type SemanticColorKey = keyof typeof semanticColors
export type ColorTuple = readonly [light: string, dark: string, tailwindClass: string]

// ── Style generation config ────────────────────────────

export interface StylesConfig {
    /** Include @layer base reset rules (apps only) */
    includeBaseLayer?: boolean
}

// ── Helpers ────────────────────────────────────────────

/** Flat object for one theme */
export function resolveTheme(mode: 'light' | 'dark'): Record<SemanticColorKey, string> {
    const i = mode === 'light' ? 0 : 1
    return Object.fromEntries(Object.entries(semanticColors).map(([k, v]) => [k, v[i]])) as Record<
        SemanticColorKey,
        string
    >
}

/** Generate color-system.css (:root light + .dark overrides) */
export function generateColorSystemCSS(): string {
    const varsBlock = (selector: string, i: number): string => {
        const lightDark = Object.fromEntries(Object.entries(semanticColors).map(([k, v]) => [k, v[i]]))
        return `${selector} {\n  --radius: 0.625rem;\n${cssVarsFlat(lightDark)}\n}`
    }

    return `/* Auto-generated by @posthog/mosaic-tokens — do not edit manually */

:root {
  color-scheme: light;
}

.dark {
  color-scheme: dark;
}

${varsBlock(':root', 0)}

${varsBlock('.dark', 1)}
`
}

/** Generate Tailwind v4 @theme color mappings (--color-* → var(--*)) */
function generateColorMappingsCSS(): string {
    return Object.keys(semanticColors)
        .map((k) => `  --color-${k}: var(--${k});`)
        .join('\n')
}

/**
 * Generate Tailwind v4 @theme + @custom-variant + optional @layer base.
 *
 * Does NOT include `@import "tailwindcss"` or `@import "color-system.css"` —
 * those are the consuming app's responsibility (they must resolve from the
 * app's node_modules, not from tokens/dist/).
 *
 * Two modes:
 *  - **Library** (includeBaseLayer: false): Just the @theme inline block
 *    so Tailwind can generate utility classes. Used by packages.
 *
 *  - **App** (includeBaseLayer: true): @theme + base layer resets.
 *    Used by apps/web, apps/storybook.
 */
export function generateStylesCSS(config: StylesConfig = {}): string {
    const { includeBaseLayer = false } = config

    const lines: string[] = [
        '/* Auto-generated by @posthog/mosaic-tokens — do not edit manually */',
        '',
        '@custom-variant dark (&:is(.dark, .dark *));',
    ]
    lines.push('')

    // ── @theme inline ──────────────────────────────────
    lines.push('@theme inline {')
    lines.push('  --animate-skeleton: skeleton 2s -1s infinite linear;')
    lines.push('')
    lines.push('  /* --- Colors --- */')
    lines.push(generateColorMappingsCSS())
    lines.push('')
    lines.push('  --color-sidebar: var(--sidebar);')
    lines.push('  --color-sidebar-foreground: var(--sidebar-foreground);')
    lines.push('  --color-sidebar-accent: var(--sidebar-accent);')
    lines.push('  --color-sidebar-accent-foreground: var(--sidebar-accent-foreground);')
    lines.push('  --color-sidebar-border: var(--sidebar-border);')
    lines.push('  --color-sidebar-ring: var(--sidebar-ring);')
    lines.push('')
    lines.push('  /* --- Spacing --- */')
    lines.push(generateSpacingCSS())
    lines.push('')
    lines.push('  /* --- Font sizes --- */')
    lines.push(generateFontSizeCSS())
    lines.push('')
    lines.push('  /* --- Font families --- */')
    lines.push(generateFontFamilyCSS())
    lines.push('')
    lines.push('  /* --- Shadows --- */')
    lines.push(generateShadowCSS())
    lines.push('')
    lines.push('  /* --- Radius (derived from --radius base) --- */')
    lines.push('  --radius-sm: calc(var(--radius) - 4px);')
    lines.push('  --radius-md: calc(var(--radius) - 2px);')
    lines.push('  --radius-lg: var(--radius);')
    lines.push('  --radius-xl: calc(var(--radius) + 4px);')
    lines.push('  --radius-2xl: calc(var(--radius) + 8px);')
    lines.push('  --radius-3xl: calc(var(--radius) + 12px);')
    lines.push('  --radius-4xl: calc(var(--radius) + 16px);')
    lines.push('')
    lines.push('  @keyframes skeleton {')
    lines.push('    to {')
    lines.push('      background-position: -200% 0;')
    lines.push('    }')
    lines.push('  }')
    lines.push('}')

    if (includeBaseLayer) {
        lines.push('')
        lines.push('@layer base {')
        lines.push('  * {')
        lines.push('    @apply border-border outline-ring/50;')
        lines.push('  }')
        lines.push('  body {')
        lines.push('    @apply bg-background text-foreground;')
        lines.push('  }')
        lines.push('}')
    }

    lines.push('')
    return lines.join('\n')
}
