# Generated by Django 4.2.29 on 2026-03-25 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import posthog.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "1066_alter_insight_saved"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posthog_ai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionPredictionModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=posthog.models.utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=400)),
                ("description", models.TextField(blank=True, default="")),
                ("event_name", models.CharField(blank=True, max_length=400, null=True)),
                ("lookback_days", models.PositiveIntegerField()),
                (
                    "action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="posthog.action",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_prediction_models",
                        to="posthog.team",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["team", "id"], name="posthog_ai__team_id_07fd1e_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="actionpredictionmodel",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("action__isnull", False), ("event_name__isnull", True)),
                    models.Q(("action__isnull", True), ("event_name__isnull", False)),
                    _connector="OR",
                ),
                name="action_or_event_name_exclusive",
            ),
        ),
    ]
