# Generated by Django 4.2.29 on 2026-03-25 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import posthog.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "1066_alter_insight_saved"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posthog_ai", "0002_actionpredictionmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionPredictionModelRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=posthog.models.utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_winning",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this run produced a winning prediction model.",
                    ),
                ),
                (
                    "model_url",
                    models.URLField(
                        help_text="S3 URL to the serialized model artifact.",
                        max_length=2000,
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Model evaluation metrics (e.g. accuracy, AUC, F1).",
                    ),
                ),
                (
                    "feature_importance",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Feature importance scores from model training.",
                    ),
                ),
                (
                    "artifact_script",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The Python script used to train and produce the model artifact.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prediction_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="posthog_ai.actionpredictionmodel",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_prediction_model_runs",
                        to="posthog.team",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["team", "id"], name="posthog_ai__team_id_9f64e3_idx"),
                    models.Index(
                        fields=["prediction_model", "-created_at"],
                        name="posthog_ai__predict_b99ec6_idx",
                    ),
                ],
            },
        ),
    ]
