# Generated by Django 4.2.29 on 2026-03-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog_ai", "0003_actionpredictionmodelrun"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actionpredictionmodelrun",
            name="artifact_script",
        ),
        migrations.AddField(
            model_name="actionpredictionmodelrun",
            name="artifact_scripts",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Python scripts used in this run. Keys: data, preprocess, train, predict.",
            ),
        ),
    ]
