# Generated by Django 4.2.29 on 2026-03-25 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0024_task_title_manually_set"),
        ("posthog_ai", "0003_actionpredictionmodelrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionpredictionmodelrun",
            name="task_run",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional sandboxed agent task run that produced this model.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prediction_model_runs",
                to="tasks.taskrun",
            ),
        ),
    ]
