# Generated by Django 4.2.29 on 2026-03-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog_ai", "0004_actionpredictionmodelrun_task_run"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionpredictionmodelrun",
            name="model_url",
            field=models.CharField(
                help_text="S3 storage path to the serialized model artifact.",
                max_length=2000,
            ),
        ),
    ]
