# Generated by Django 4.2.29 on 2026-03-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog_ai", "0005_add_winning_run_and_experiment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionpredictionmodelrun",
            name="notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Agent lab notebook: what was tried, what was observed, what to try next.",
            ),
        ),
    ]
