# Generated by Django 4.2.29 on 2026-03-25 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0024_task_title_manually_set"),
        ("posthog_ai", "0005_alter_actionpredictionmodelrun_model_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionpredictionmodel",
            name="task_run",
            field=models.ForeignKey(
                blank=True,
                help_text="Sandbox task run that trains this prediction model.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_prediction_models",
                to="tasks.taskrun",
            ),
        ),
    ]
