# Generated by Django 4.2.28 on 2026-03-18 00:00

from django.db import migrations, models


# NOTE: this migration is a no op in the db but updates django state to include
# the queued DataModelingJobStatus choice.
class Migration(migrations.Migration):
    dependencies = [
        ("data_warehouse", "0029_team_data_warehouse_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datamodelingjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("Cancelled", "Cancelled"),
                    ("Completed", "Completed"),
                    ("Failed", "Failed"),
                    ("Queued", "Queued"),
                    ("Running", "Running"),
                ],
                default="Running",
                max_length=400,
            ),
        ),
    ]
