# Generated by Django 4.2.29 on 2026-03-23 11:47

import django.db.models.deletion
from django.db import migrations, models


def update_content_types(apps, schema_editor):
    """Update content types from posthog to feature_flags app."""
    ContentType = apps.get_model("contenttypes", "ContentType")

    models_to_move = [
        "evaluationcontext",
        "featureflag",
        "featureflagdashboards",
        "featureflagevaluationcontext",
        "featureflagevaluationtag",
        "featureflagoverride",
        "scheduledchange",
        "teamdefaultevaluationcontext",
        "teamdefaultevaluationtag",
        "featureflaghashkeyoverride",
    ]

    for model_name in models_to_move:
        ContentType.objects.filter(app_label="posthog", model=model_name).update(app_label="feature_flags")


def reverse_content_types(apps, schema_editor):
    """Reverse content type updates."""
    ContentType = apps.get_model("contenttypes", "ContentType")

    models_to_move = [
        "evaluationcontext",
        "featureflag",
        "featureflagdashboards",
        "featureflagevaluationcontext",
        "featureflagevaluationtag",
        "featureflagoverride",
        "scheduledchange",
        "teamdefaultevaluationcontext",
        "teamdefaultevaluationtag",
        "featureflaghashkeyoverride",
    ]

    for model_name in models_to_move:
        ContentType.objects.filter(app_label="feature_flags", model=model_name).update(app_label="posthog")


class Migration(migrations.Migration):
    dependencies = [
        ("product_tours", "0007_migrate_feature_flags_models"),
        ("early_access_features", "0006_migrate_feature_flags_models"),
        ("ee", "0041_migrate_feature_flags_models"),
        ("experiments", "0002_migrate_feature_flags_models"),
        ("feature_flags", "0002_migrate_feature_flags_models"),
        ("posthog", "1063_remove_surveyresponsearchive_survey_and_more"),
    ]

    operations = [
        # Update FK references first — must happen while posthog.FeatureFlag
        # still exists in state so Django can resolve the old FK target
        migrations.AlterField(
            model_name="survey",
            name="internal_response_sampling_flag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="surveys_internal_response_sampling_flag",
                related_query_name="surveys_internal_response_sampling_flag",
                to="feature_flags.featureflag",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="internal_targeting_flag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="surveys_internal_targeting_flag",
                related_query_name="survey_internal_targeting_flag",
                to="feature_flags.featureflag",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="linked_flag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="surveys_linked_flag",
                related_query_name="survey_linked_flag",
                to="feature_flags.featureflag",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="targeting_flag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="surveys_targeting_flag",
                related_query_name="survey_targeting_flag",
                to="feature_flags.featureflag",
            ),
        ),
        migrations.AlterField(
            model_name="taggeditem",
            name="feature_flag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tagged_items",
                to="feature_flags.featureflag",
            ),
        ),
        # State-only: remove models from posthog app state (tables stay)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="featureflag",
                    name="analytics_dashboards",
                ),
                migrations.RemoveField(
                    model_name="featureflag",
                    name="created_by",
                ),
                migrations.RemoveField(
                    model_name="featureflag",
                    name="last_modified_by",
                ),
                migrations.RemoveField(
                    model_name="featureflag",
                    name="team",
                ),
                migrations.RemoveField(
                    model_name="featureflag",
                    name="usage_dashboard",
                ),
                migrations.RemoveField(
                    model_name="featureflagdashboards",
                    name="dashboard",
                ),
                migrations.RemoveField(
                    model_name="featureflagdashboards",
                    name="feature_flag",
                ),
                migrations.AlterUniqueTogether(
                    name="featureflagevaluationcontext",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="featureflagevaluationcontext",
                    name="evaluation_context",
                ),
                migrations.RemoveField(
                    model_name="featureflagevaluationcontext",
                    name="feature_flag",
                ),
                migrations.AlterUniqueTogether(
                    name="featureflagevaluationtag",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="featureflagevaluationtag",
                    name="feature_flag",
                ),
                migrations.RemoveField(
                    model_name="featureflagevaluationtag",
                    name="tag",
                ),
                migrations.RemoveField(
                    model_name="featureflagoverride",
                    name="feature_flag",
                ),
                migrations.RemoveField(
                    model_name="featureflagoverride",
                    name="team",
                ),
                migrations.RemoveField(
                    model_name="featureflagoverride",
                    name="user",
                ),
                migrations.RemoveField(
                    model_name="scheduledchange",
                    name="created_by",
                ),
                migrations.RemoveField(
                    model_name="scheduledchange",
                    name="team",
                ),
                migrations.AlterUniqueTogether(
                    name="teamdefaultevaluationcontext",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="teamdefaultevaluationcontext",
                    name="evaluation_context",
                ),
                migrations.RemoveField(
                    model_name="teamdefaultevaluationcontext",
                    name="team",
                ),
                migrations.AlterUniqueTogether(
                    name="teamdefaultevaluationtag",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="teamdefaultevaluationtag",
                    name="tag",
                ),
                migrations.RemoveField(
                    model_name="teamdefaultevaluationtag",
                    name="team",
                ),
                migrations.RemoveField(
                    model_name="featureflaghashkeyoverride",
                    name="person",
                ),
                migrations.RemoveField(
                    model_name="featureflaghashkeyoverride",
                    name="team",
                ),
                migrations.DeleteModel(
                    name="EvaluationContext",
                ),
                migrations.DeleteModel(
                    name="FeatureFlag",
                ),
                migrations.DeleteModel(
                    name="FeatureFlagDashboards",
                ),
                migrations.DeleteModel(
                    name="FeatureFlagEvaluationContext",
                ),
                migrations.DeleteModel(
                    name="FeatureFlagEvaluationTag",
                ),
                migrations.DeleteModel(
                    name="FeatureFlagOverride",
                ),
                migrations.DeleteModel(
                    name="ScheduledChange",
                ),
                migrations.DeleteModel(
                    name="TeamDefaultEvaluationContext",
                ),
                migrations.DeleteModel(
                    name="TeamDefaultEvaluationTag",
                ),
                migrations.DeleteModel(
                    name="FeatureFlagHashKeyOverride",
                ),
            ],
            database_operations=[],
        ),
        # Update content types
        migrations.RunPython(update_content_types, reverse_content_types),
    ]
