# Generated by Django 4.2.29 on 2026-03-24 08:02

import django.db.models.deletion
from django.db import migrations, models

MODELS_TO_MOVE = [
    "evaluationcontext",
    "featureflag",
    "featureflagdashboards",
    "featureflagevaluationcontext",
    "featureflagevaluationtag",
    "featureflagoverride",
    "scheduledchange",
    "teamdefaultevaluationcontext",
    "teamdefaultevaluationtag",
    "featureflaghashkeyoverride",
]


def _move_content_types(apps, schema_editor, from_label, to_label):
    db_alias = schema_editor.connection.alias
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")

    for model_name in MODELS_TO_MOVE:
        source = ContentType.objects.using(db_alias).filter(app_label=from_label, model=model_name).first()
        target = ContentType.objects.using(db_alias).filter(app_label=to_label, model=model_name).first()

        if source and target:
            Permission.objects.using(db_alias).filter(content_type=source).update(content_type=target)
            source.delete(using=db_alias)
        elif source:
            source.app_label = to_label
            source.save(using=db_alias)


def update_content_types(apps, schema_editor):
    _move_content_types(apps, schema_editor, "posthog", "feature_flags")


def reverse_content_types(apps, schema_editor):
    _move_content_types(apps, schema_editor, "feature_flags", "posthog")


class Migration(migrations.Migration):
    dependencies = [
        ("early_access_features", "0006_alter_earlyaccessfeature_feature_flag"),
        ("ee", "0041_alter_featureflagroleaccess_feature_flag"),
        ("feature_flags", "0002_featureflaghashkeyoverride_evaluationcontext_and_more"),
        ("product_tours", "0007_alter_producttour_internal_targeting_flag_and_more"),
        ("surveys", "0002_alter_survey_internal_response_sampling_flag_and_more"),
        ("experiments", "0002_alter_experiment_feature_flag"),
        ("posthog", "1066_alter_insight_saved"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="featureflag",
                    name="analytics_dashboards",
                ),
                migrations.RemoveField(
                    model_name="featureflag",
                    name="created_by",
                ),
                migrations.RemoveField(
                    model_name="featureflag",
                    name="last_modified_by",
                ),
                migrations.RemoveField(
                    model_name="featureflag",
                    name="team",
                ),
                migrations.RemoveField(
                    model_name="featureflag",
                    name="usage_dashboard",
                ),
                migrations.RemoveField(
                    model_name="featureflagdashboards",
                    name="dashboard",
                ),
                migrations.RemoveField(
                    model_name="featureflagdashboards",
                    name="feature_flag",
                ),
                migrations.AlterUniqueTogether(
                    name="featureflagevaluationcontext",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="featureflagevaluationcontext",
                    name="evaluation_context",
                ),
                migrations.RemoveField(
                    model_name="featureflagevaluationcontext",
                    name="feature_flag",
                ),
                migrations.AlterUniqueTogether(
                    name="featureflagevaluationtag",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="featureflagevaluationtag",
                    name="feature_flag",
                ),
                migrations.RemoveField(
                    model_name="featureflagevaluationtag",
                    name="tag",
                ),
                migrations.RemoveField(
                    model_name="featureflagoverride",
                    name="feature_flag",
                ),
                migrations.RemoveField(
                    model_name="featureflagoverride",
                    name="team",
                ),
                migrations.RemoveField(
                    model_name="featureflagoverride",
                    name="user",
                ),
                migrations.RemoveField(
                    model_name="scheduledchange",
                    name="created_by",
                ),
                migrations.RemoveField(
                    model_name="scheduledchange",
                    name="team",
                ),
                migrations.AlterUniqueTogether(
                    name="teamdefaultevaluationcontext",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="teamdefaultevaluationcontext",
                    name="evaluation_context",
                ),
                migrations.RemoveField(
                    model_name="teamdefaultevaluationcontext",
                    name="team",
                ),
                migrations.AlterUniqueTogether(
                    name="teamdefaultevaluationtag",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="teamdefaultevaluationtag",
                    name="tag",
                ),
                migrations.RemoveField(
                    model_name="teamdefaultevaluationtag",
                    name="team",
                ),
                migrations.RemoveField(
                    model_name="featureflaghashkeyoverride",
                    name="person",
                ),
                migrations.RemoveField(
                    model_name="featureflaghashkeyoverride",
                    name="team",
                ),
                migrations.AlterField(
                    model_name="taggeditem",
                    name="feature_flag",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="feature_flags.featureflag",
                    ),
                ),
                migrations.DeleteModel(
                    name="EvaluationContext",
                ),
                migrations.DeleteModel(
                    name="FeatureFlag",
                ),
                migrations.DeleteModel(
                    name="FeatureFlagDashboards",
                ),
                migrations.DeleteModel(
                    name="FeatureFlagEvaluationContext",
                ),
                migrations.DeleteModel(
                    name="FeatureFlagEvaluationTag",
                ),
                migrations.DeleteModel(
                    name="FeatureFlagOverride",
                ),
                migrations.DeleteModel(
                    name="ScheduledChange",
                ),
                migrations.DeleteModel(
                    name="TeamDefaultEvaluationContext",
                ),
                migrations.DeleteModel(
                    name="TeamDefaultEvaluationTag",
                ),
                migrations.DeleteModel(
                    name="FeatureFlagHashKeyOverride",
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(update_content_types, reverse_content_types),
    ]
