# Generated by Django 4.2.29 on 2026-04-06 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "1085_ducklake_backfill_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="duckgresserver",
            name="team",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="duckgres_server",
                to="posthog.team",
            ),
        ),
        migrations.AlterField(
            model_name="ducklakecatalog",
            name="team",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ducklake_catalog",
                to="posthog.team",
            ),
        ),
    ]
