/**
 * Ghost Run Cleanup Script
 *
 * Context: During the March 18-19, 2026 incident, a cross-routing bug in the
 * Cyclotron job queue caused workflow invocations to be executed multiple times
 * per trigger event. This created "ghost runs" - duplicate workflow runs that
 * share the same trigger event but have different run IDs. These ghost runs
 * are still alive in the Cyclotron database, progressing through delay steps
 * and sending duplicate emails/notifications at each action step.
 *
 * This script:
 * 1. Queries ClickHouse to find workflow runs that share the same trigger event
 *    (same team + same workflow + same event UUID = duplicates)
 * 2. For each group of duplicates, keeps the earliest run and marks the rest as ghosts
 * 3. Outputs the ghost run IDs that should be marked as 'completed' in the Cyclotron DB
 *
 * Usage:
 *   Step 1: Export ClickHouse data to CSV using the query in getClickHouseQuery()
 *   Step 2: Run this script with the CSV to get ghost run IDs
 *   Step 3: Use the generated SQL to clean up the Cyclotron DB
 */
import * as fs from 'fs'
import * as path from 'path'

interface LogEntry {
    team_id: string
    run_id: string
    workflow_id: string
    message: string
    timestamp: string
}

interface GhostRunResult {
    teamId: string
    ghostRunIds: string[]
    legitimateRunId: string
    eventId: string
    totalRuns: number
}

/**
 * Returns the ClickHouse query to extract workflow trigger/resume data
 * for the incident window. Run this on ClickHouse and save the result as CSV.
 */
export function getClickHouseQuery(teamIds: number[]): string {
    const teamIdList = teamIds.join(', ')
    return `
SELECT
    team_id,
    instance_id AS run_id,
    log_source_id AS workflow_id,
    message,
    toString(timestamp) AS timestamp
FROM log_entries
WHERE timestamp BETWEEN '2026-03-18 14:53:00' AND '2026-03-19 11:30:00'
  AND message LIKE 'Resuming workflow%'
  AND team_id IN (${teamIdList})
ORDER BY team_id, message, instance_id
`
}

/**
 * Extracts the event ID from a workflow log message.
 * Messages look like: "Resuming workflow execution at [Action:...] on [Event:EVENT_ID|event_name|timestamp]"
 */
export function extractEventId(message: string): string | null {
    const match = message.match(/\[Event:([^|]+)\|/)
    return match ? match[1] : null
}

/**
 * Extracts the action ID from a workflow log message.
 * Messages look like: "Resuming workflow execution at [Action:ACTION_ID] on [Event:...]"
 */
export function extractActionId(message: string): string | null {
    const match = message.match(/\[Action:([^\]]+)\]/)
    return match ? match[1] : null
}

/**
 * Parses CSV data and identifies ghost runs.
 *
 * Groups runs by (team_id, workflow_id, event_id). Within each group,
 * the earliest run (by timestamp) is kept as legitimate, and the rest
 * are marked as ghosts.
 */
export function identifyGhostRuns(entries: LogEntry[]): GhostRunResult[] {
    // Group by team_id + workflow_id + event_id
    const groups = new Map<string, { runId: string; timestamp: string }[]>()

    for (const entry of entries) {
        const eventId = extractEventId(entry.message)
        if (!eventId) {
            continue
        }

        const key = `${entry.team_id}:${entry.workflow_id}:${eventId}`

        if (!groups.has(key)) {
            groups.set(key, [])
        }

        const group = groups.get(key)!
        // Only add each run_id once per group
        if (!group.some((r) => r.runId === entry.run_id)) {
            group.push({ runId: entry.run_id, timestamp: entry.timestamp })
        }
    }

    // For each group with duplicates, identify ghost runs
    const results: GhostRunResult[] = []

    for (const [key, runs] of groups) {
        if (runs.length <= 1) {
            continue
        }

        const parts = key.split(':')
        const teamId = parts[0]
        const eventId = parts.slice(2).join(':')

        // Sort by timestamp, keep the earliest as legitimate
        runs.sort((a, b) => a.timestamp.localeCompare(b.timestamp))

        const legitimateRun = runs[0]
        const ghostRuns = runs.slice(1)

        results.push({
            teamId,
            ghostRunIds: ghostRuns.map((r) => r.runId),
            legitimateRunId: legitimateRun.runId,
            eventId,
            totalRuns: runs.length,
        })
    }

    return results
}

/**
 * Generates SQL to mark ghost runs as completed in the old Cyclotron DB.
 * Only updates jobs that are currently in 'available' state (safe to update).
 */
export function generateCleanupSQL(ghostRunIds: string[]): string {
    if (ghostRunIds.length === 0) {
        return '-- No ghost runs to clean up'
    }

    const idList = ghostRunIds.map((id) => `'${id}'`).join(',\n    ')

    return `-- Ghost run cleanup: mark duplicate workflow runs as completed
-- Generated by cleanup-ghost-runs script
-- Total ghost runs: ${ghostRunIds.length}
--
-- IMPORTANT: Only updates jobs in 'available' state (not currently running).
-- Jobs in 'running' state are skipped to avoid interfering with active processing.

UPDATE cyclotron_jobs
SET state = 'completed',
    lock_id = NULL,
    last_heartbeat = NULL,
    last_transition = NOW(),
    transition_count = transition_count + 1
WHERE id IN (
    ${idList}
)
AND state = 'available';`
}

/**
 * Parses a CSV string into LogEntry objects.
 * Handles quoted fields with commas.
 */
export function parseCSV(csv: string): LogEntry[] {
    const lines = csv.trim().split('\n')
    const header = lines[0]
    if (!header) {
        return []
    }

    const entries: LogEntry[] = []

    for (let i = 1; i < lines.length; i++) {
        const line = lines[i]
        if (!line.trim()) {
            continue
        }

        // Simple CSV parsing: split by comma but respect quoted fields
        const fields: string[] = []
        let current = ''
        let inQuotes = false

        for (const char of line) {
            if (char === '"') {
                inQuotes = !inQuotes
            } else if (char === ',' && !inQuotes) {
                fields.push(current.trim())
                current = ''
            } else {
                current += char
            }
        }
        fields.push(current.trim())

        if (fields.length >= 5) {
            entries.push({
                team_id: fields[0].replace(/,/g, ''),
                run_id: fields[1],
                workflow_id: fields[2],
                message: fields[3],
                timestamp: fields[4],
            })
        }
    }

    return entries
}

/**
 * Main cleanup function. Takes a CSV file path and outputs cleanup SQL.
 */
export function processCleanup(csvPath: string): {
    results: GhostRunResult[]
    allGhostRunIds: string[]
    sql: string
    summary: string
} {
    const csv = fs.readFileSync(csvPath, 'utf-8')
    const entries = parseCSV(csv)
    const results = identifyGhostRuns(entries)

    const allGhostRunIds = results.flatMap((r) => r.ghostRunIds)

    // Summary per team
    const teamSummary = new Map<string, { ghostRuns: number; affectedEvents: number }>()
    for (const result of results) {
        const existing = teamSummary.get(result.teamId) || { ghostRuns: 0, affectedEvents: 0 }
        existing.ghostRuns += result.ghostRunIds.length
        existing.affectedEvents += 1
        teamSummary.set(result.teamId, existing)
    }

    let summary = `Ghost Run Cleanup Summary\n`
    summary += `========================\n`
    summary += `Total ghost runs: ${allGhostRunIds.length}\n`
    summary += `Total affected events: ${results.length}\n`
    summary += `Total affected teams: ${teamSummary.size}\n\n`
    summary += `Per team:\n`

    for (const [teamId, stats] of teamSummary) {
        summary += `  Team ${teamId}: ${stats.ghostRuns} ghost runs across ${stats.affectedEvents} events\n`
    }

    const sql = generateCleanupSQL(allGhostRunIds)

    return { results, allGhostRunIds, sql, summary }
}

// CLI entrypoint
if (require.main === module) {
    const csvPath = process.argv[2]
    if (!csvPath) {
        console.log('Usage: npx ts-node cleanup-ghost-runs.ts <csv-file>')
        console.log('')
        console.log('Step 1: Run the ClickHouse query to get the data:')
        console.log(
            getClickHouseQuery([
                277932, 281194, 240217, 243819, 78051, 47337, 110739, 262324, 70616, 103207, 73108, 122682, 118319,
                81505, 163576, 76160, 127158, 189310, 106363, 105711, 224119, 121623,
            ])
        )
        console.log('')
        console.log('Step 2: Save the result as CSV and run this script with the path')
        process.exit(1)
    }

    const { summary, sql, allGhostRunIds } = processCleanup(csvPath)

    console.log(summary)
    console.log('')

    // Write SQL to file
    const sqlPath = path.join(path.dirname(csvPath), 'ghost-run-cleanup.sql')
    fs.writeFileSync(sqlPath, sql)
    console.log(`SQL written to: ${sqlPath}`)

    // Write ghost IDs to file
    const idsPath = path.join(path.dirname(csvPath), 'ghost-run-ids.txt')
    fs.writeFileSync(idsPath, allGhostRunIds.join('\n'))
    console.log(`Ghost run IDs written to: ${idsPath}`)
}
