# Generated by Django 4.2.29 on 2026-03-23 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feature_flags", "0002_migrate_feature_flags_models"),
        ("ee", "0040_scimrequestlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureflagroleaccess",
            name="feature_flag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access",
                related_query_name="access",
                to="feature_flags.featureflag",
            ),
        ),
    ]
