# Generated by Django 4.2.29 on 2026-03-24 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feature_flags", "0002_featureflaghashkeyoverride_evaluationcontext_and_more"),
        ("ee", "0040_scimrequestlog"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="featureflagroleaccess",
                    name="feature_flag",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access",
                        related_query_name="access",
                        to="feature_flags.featureflag",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
