# Generated by Django 4.2.29 on 2026-03-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signals", "0010_add_data_import_signal_source_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signalreportartefact",
            name="type",
            field=models.CharField(
                choices=[
                    ("video_segment", "Video Segment"),
                    ("safety_judgment", "Safety Judgment"),
                    ("actionability_judgment", "Actionability Judgment"),
                    ("priority_judgment", "Priority Judgment"),
                    ("signal_finding", "Signal Finding"),
                ],
                max_length=100,
            ),
        ),
    ]
