# Generated by Django 4.2.29 on 2026-03-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signals", "0010_add_data_import_signal_source_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signalsourceconfig",
            name="source_product",
            field=models.CharField(
                choices=[
                    ("session_replay", "Session replay"),
                    ("llm_analytics", "LLM analytics"),
                    ("github", "GitHub"),
                    ("linear", "Linear"),
                    ("zendesk", "Zendesk"),
                    ("conversations", "Conversations"),
                ],
                max_length=100,
            ),
        ),
    ]
