# Generated by Django 4.2.29 on 2026-03-24 13:27

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("visual_review", "0003_backfill_team_id"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="artifact",
            managers=[
                ("unscoped", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="repo",
            managers=[
                ("unscoped", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="run",
            managers=[
                ("unscoped", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="runsnapshot",
            managers=[
                ("unscoped", django.db.models.manager.Manager()),
            ],
        ),
    ]
