# Generated by Django 4.2.29 on 2026-03-27 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("visual_review", "0004_use_product_team_model"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="artifact",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="repo",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="run",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="runsnapshot",
            managers=[],
        ),
    ]
