# Generated by Django 4.2.29 on 2026-03-23 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feature_flags", "0002_migrate_feature_flags_models"),
        ("early_access_features", "0005_clear_concept_super_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="earlyaccessfeature",
            name="feature_flag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="features",
                related_query_name="feature",
                to="feature_flags.featureflag",
            ),
        ),
    ]
