# Generated by Django 4.2.29 on 2026-03-24 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feature_flags", "0002_featureflaghashkeyoverride_evaluationcontext_and_more"),
        ("early_access_features", "0005_clear_concept_super_groups"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="earlyaccessfeature",
                    name="feature_flag",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="features",
                        related_query_name="feature",
                        to="feature_flags.featureflag",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
