# Generated by Django 4.2.29 on 2026-03-23 11:47

import django.utils.timezone
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import posthog.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "1060_alter_integration_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feature_flags", "0001_team_feature_flag_defaults_config"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="FeatureFlagHashKeyOverride",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("feature_flag_key", models.CharField(max_length=400)),
                        ("hash_key", models.CharField(max_length=400)),
                    ],
                    options={
                        "db_table": "posthog_featureflaghashkeyoverride",
                        "managed": False,
                    },
                ),
                migrations.CreateModel(
                    name="EvaluationContext",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=posthog.models.utils.uuid7,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("name", models.CharField(max_length=255)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "team",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="evaluation_context_set",
                                to="posthog.team",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "posthog_evaluationcontext",
                    },
                ),
                migrations.CreateModel(
                    name="FeatureFlag",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("key", models.CharField(max_length=400)),
                        ("name", models.TextField(blank=True)),
                        ("filters", models.JSONField(default=dict)),
                        ("rollout_percentage", models.IntegerField(blank=True, null=True)),
                        ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                        ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                        ("deleted", models.BooleanField(default=False)),
                        ("active", models.BooleanField(default=True)),
                        ("version", models.IntegerField(default=1, null=True)),
                        ("rollback_conditions", models.JSONField(blank=True, null=True)),
                        ("performed_rollback", models.BooleanField(blank=True, null=True)),
                        (
                            "ensure_experience_continuity",
                            models.BooleanField(blank=True, default=False, null=True),
                        ),
                        (
                            "has_enriched_analytics",
                            models.BooleanField(blank=True, default=False, null=True),
                        ),
                        (
                            "is_remote_configuration",
                            models.BooleanField(blank=True, default=False, null=True),
                        ),
                        (
                            "has_encrypted_payloads",
                            models.BooleanField(blank=True, default=False, null=True),
                        ),
                        (
                            "evaluation_runtime",
                            models.CharField(
                                blank=True,
                                choices=[
                                    ("server", "Server"),
                                    ("client", "Client"),
                                    ("all", "All"),
                                ],
                                default="all",
                                help_text="Specifies where this feature flag should be evaluated",
                                max_length=10,
                                null=True,
                            ),
                        ),
                        (
                            "bucketing_identifier",
                            models.CharField(
                                blank=True,
                                choices=[
                                    ("distinct_id", "User ID (default)"),
                                    ("device_id", "Device ID"),
                                ],
                                default="distinct_id",
                                help_text="Identifier used for bucketing users into rollout and variants",
                                max_length=50,
                                null=True,
                            ),
                        ),
                        (
                            "last_called_at",
                            models.DateTimeField(
                                blank=True,
                                help_text="Last time this feature flag was called (from $feature_flag_called events)",
                                null=True,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "posthog_featureflag",
                    },
                ),
                migrations.CreateModel(
                    name="FeatureFlagOverride",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("override_value", models.JSONField()),
                        (
                            "feature_flag",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="feature_flags.featureflag",
                            ),
                        ),
                        (
                            "team",
                            models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="posthog.team"),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "posthog_featureflagoverride",
                    },
                ),
                migrations.CreateModel(
                    name="FeatureFlagEvaluationTag",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "feature_flag",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="evaluation_tags",
                                to="feature_flags.featureflag",
                            ),
                        ),
                        (
                            "tag",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="evaluation_flags",
                                to="posthog.tag",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "posthog_featureflagevaluationtag",
                    },
                ),
                migrations.CreateModel(
                    name="FeatureFlagEvaluationContext",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=posthog.models.utils.uuid7,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "evaluation_context",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="feature_flags",
                                to="feature_flags.evaluationcontext",
                            ),
                        ),
                        (
                            "feature_flag",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="flag_evaluation_contexts",
                                to="feature_flags.featureflag",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "posthog_featureflagevaluationcontext",
                    },
                ),
                migrations.CreateModel(
                    name="FeatureFlagDashboards",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                        ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                        (
                            "dashboard",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="posthog.dashboard",
                            ),
                        ),
                        (
                            "feature_flag",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="feature_flags.featureflag",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "posthog_featureflagdashboards",
                    },
                ),
                migrations.AddField(
                    model_name="featureflag",
                    name="analytics_dashboards",
                    field=models.ManyToManyField(
                        related_name="analytics_dashboards",
                        related_query_name="analytics_dashboard",
                        through="feature_flags.FeatureFlagDashboards",
                        to="posthog.dashboard",
                    ),
                ),
                migrations.AddField(
                    model_name="featureflag",
                    name="created_by",
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                migrations.AddField(
                    model_name="featureflag",
                    name="last_modified_by",
                    field=models.ForeignKey(
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_feature_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                migrations.AddField(
                    model_name="featureflag",
                    name="team",
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="posthog.team"),
                ),
                migrations.AddField(
                    model_name="featureflag",
                    name="usage_dashboard",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="posthog.dashboard",
                    ),
                ),
                migrations.CreateModel(
                    name="TeamDefaultEvaluationTag",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=posthog.models.utils.uuid7,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "tag",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="team_defaults",
                                to="posthog.tag",
                            ),
                        ),
                        (
                            "team",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="default_evaluation_contexts",
                                to="posthog.team",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "posthog_teamdefaultevaluationtag",
                        "unique_together": {("team", "tag")},
                    },
                ),
                migrations.CreateModel(
                    name="TeamDefaultEvaluationContext",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=posthog.models.utils.uuid7,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "evaluation_context",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="team_defaults",
                                to="feature_flags.evaluationcontext",
                            ),
                        ),
                        (
                            "team",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="default_evaluation_context_set",
                                to="posthog.team",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "posthog_teamdefaultevaluationcontext",
                        "unique_together": {("team", "evaluation_context")},
                    },
                ),
                migrations.CreateModel(
                    name="ScheduledChange",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("record_id", models.CharField(max_length=200)),
                        (
                            "model_name",
                            models.CharField(choices=[("FeatureFlag", "feature flag")], max_length=100),
                        ),
                        ("payload", models.JSONField(default=dict)),
                        ("scheduled_at", models.DateTimeField()),
                        ("executed_at", models.DateTimeField(blank=True, null=True)),
                        (
                            "failure_reason",
                            models.CharField(blank=True, max_length=400, null=True),
                        ),
                        ("failure_count", models.IntegerField(default=0)),
                        ("is_recurring", models.BooleanField(default=False)),
                        (
                            "recurrence_interval",
                            models.CharField(
                                blank=True,
                                choices=[
                                    ("daily", "daily"),
                                    ("weekly", "weekly"),
                                    ("monthly", "monthly"),
                                    ("yearly", "yearly"),
                                ],
                                max_length=20,
                                null=True,
                            ),
                        ),
                        ("last_executed_at", models.DateTimeField(blank=True, null=True)),
                        ("end_date", models.DateTimeField(blank=True, null=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "created_by",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "team",
                            models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="posthog.team"),
                        ),
                    ],
                    options={
                        "db_table": "posthog_scheduledchange",
                        "indexes": [
                            models.Index(
                                fields=["scheduled_at", "executed_at"],
                                name="posthog_sch_schedul_c3687e_idx",
                            )
                        ],
                    },
                ),
                migrations.AddConstraint(
                    model_name="featureflagoverride",
                    constraint=models.UniqueConstraint(
                        fields=("user", "feature_flag", "team"),
                        name="unique feature flag for a user/team combo",
                    ),
                ),
                migrations.AlterUniqueTogether(
                    name="featureflagevaluationtag",
                    unique_together={("feature_flag", "tag")},
                ),
                migrations.AlterUniqueTogether(
                    name="featureflagevaluationcontext",
                    unique_together={("feature_flag", "evaluation_context")},
                ),
                migrations.AddConstraint(
                    model_name="featureflagdashboards",
                    constraint=models.UniqueConstraint(
                        fields=("feature_flag", "dashboard"),
                        name="unique feature flag for a dashboard",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="featureflag",
                    constraint=models.UniqueConstraint(fields=("team", "key"), name="unique key for team"),
                ),
                migrations.AlterUniqueTogether(
                    name="evaluationcontext",
                    unique_together={("team", "name")},
                ),
            ],
            database_operations=[],
        ),
    ]
