# Generated by Django 4.2.29 on 2026-03-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0025_email_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="signal_emitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["team", "signal_emitted_at", "created_at"],
                name="posthog_con_signal_emit_idx",
            ),
        ),
    ]
