# Generated by Django 4.2.29 on 2026-03-24 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feature_flags", "0002_featureflaghashkeyoverride_evaluationcontext_and_more"),
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="survey",
                    name="internal_response_sampling_flag",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="surveys_internal_response_sampling_flag",
                        related_query_name="surveys_internal_response_sampling_flag",
                        to="feature_flags.featureflag",
                    ),
                ),
                migrations.AlterField(
                    model_name="survey",
                    name="internal_targeting_flag",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="surveys_internal_targeting_flag",
                        related_query_name="survey_internal_targeting_flag",
                        to="feature_flags.featureflag",
                    ),
                ),
                migrations.AlterField(
                    model_name="survey",
                    name="linked_flag",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="surveys_linked_flag",
                        related_query_name="survey_linked_flag",
                        to="feature_flags.featureflag",
                    ),
                ),
                migrations.AlterField(
                    model_name="survey",
                    name="targeting_flag",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="surveys_targeting_flag",
                        related_query_name="survey_targeting_flag",
                        to="feature_flags.featureflag",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
