# Generated by Django 4.2.29 on 2026-03-19 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0024_task_title_manually_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent task for side chats and forks in PostHog Code",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subtasks",
                to="tasks.task",
            ),
        ),
    ]
