import {
    KAFKA_APP_METRICS_2,
    KAFKA_CLICKHOUSE_AI_EVENTS_JSON,
    KAFKA_CLICKHOUSE_HEATMAP_EVENTS,
    KAFKA_CLICKHOUSE_TOPHOG,
    KAFKA_EVENTS_JSON,
    KAFKA_EVENTS_PLUGIN_INGESTION_ASYNC,
    KAFKA_EVENTS_PLUGIN_INGESTION_DLQ,
    KAFKA_EVENTS_PLUGIN_INGESTION_OVERFLOW,
    KAFKA_GROUPS,
    KAFKA_INGESTION_WARNINGS,
    KAFKA_LOG_ENTRIES,
    KAFKA_PERSON,
    KAFKA_PERSON_DISTINCT_ID,
} from '../../../config/kafka-topics'
import {
    APP_METRICS_OUTPUT,
    DLQ_OUTPUT,
    GROUPS_OUTPUT,
    INGESTION_WARNINGS_OUTPUT,
    LOG_ENTRIES_OUTPUT,
    OVERFLOW_OUTPUT,
    TOPHOG_OUTPUT,
} from '../../common/outputs'
import { IngestionOutputsBuilder } from '../../outputs/ingestion-outputs-builder'
import {
    AI_EVENTS_OUTPUT,
    ASYNC_OUTPUT,
    EVENTS_OUTPUT,
    HEATMAPS_OUTPUT,
    PERSONS_OUTPUT,
    PERSON_DISTINCT_IDS_OUTPUT,
} from '../outputs'
import { DEFAULT_PRODUCER, ProducerName } from './producers'

/** Config type for all analytics ingestion output keys. */
export type IngestionOutputsConfig = {
    INGESTION_OUTPUT_EVENTS_TOPIC: string
    INGESTION_OUTPUT_EVENTS_PRODUCER: ProducerName

    INGESTION_OUTPUT_AI_EVENTS_TOPIC: string
    INGESTION_OUTPUT_AI_EVENTS_PRODUCER: ProducerName

    INGESTION_OUTPUT_HEATMAPS_TOPIC: string
    INGESTION_OUTPUT_HEATMAPS_PRODUCER: ProducerName

    INGESTION_OUTPUT_INGESTION_WARNINGS_TOPIC: string
    INGESTION_OUTPUT_INGESTION_WARNINGS_PRODUCER: ProducerName

    INGESTION_OUTPUT_DLQ_TOPIC: string
    INGESTION_OUTPUT_DLQ_PRODUCER: ProducerName

    INGESTION_OUTPUT_OVERFLOW_TOPIC: string
    INGESTION_OUTPUT_OVERFLOW_PRODUCER: ProducerName

    INGESTION_OUTPUT_ASYNC_TOPIC: string
    INGESTION_OUTPUT_ASYNC_PRODUCER: ProducerName

    INGESTION_OUTPUT_GROUPS_TOPIC: string
    INGESTION_OUTPUT_GROUPS_PRODUCER: ProducerName

    INGESTION_OUTPUT_PERSONS_TOPIC: string
    INGESTION_OUTPUT_PERSONS_PRODUCER: ProducerName

    INGESTION_OUTPUT_PERSON_DISTINCT_IDS_TOPIC: string
    INGESTION_OUTPUT_PERSON_DISTINCT_IDS_PRODUCER: ProducerName

    INGESTION_OUTPUT_APP_METRICS_TOPIC: string
    INGESTION_OUTPUT_APP_METRICS_PRODUCER: ProducerName

    INGESTION_OUTPUT_LOG_ENTRIES_TOPIC: string
    INGESTION_OUTPUT_LOG_ENTRIES_PRODUCER: ProducerName

    INGESTION_OUTPUT_TOPHOG_TOPIC: string
    INGESTION_OUTPUT_TOPHOG_PRODUCER: ProducerName
}

export function getDefaultIngestionOutputsConfig(): IngestionOutputsConfig {
    return {
        INGESTION_OUTPUT_EVENTS_TOPIC: KAFKA_EVENTS_JSON,
        INGESTION_OUTPUT_EVENTS_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_AI_EVENTS_TOPIC: KAFKA_CLICKHOUSE_AI_EVENTS_JSON,
        INGESTION_OUTPUT_AI_EVENTS_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_HEATMAPS_TOPIC: KAFKA_CLICKHOUSE_HEATMAP_EVENTS,
        INGESTION_OUTPUT_HEATMAPS_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_INGESTION_WARNINGS_TOPIC: KAFKA_INGESTION_WARNINGS,
        INGESTION_OUTPUT_INGESTION_WARNINGS_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_DLQ_TOPIC: KAFKA_EVENTS_PLUGIN_INGESTION_DLQ,
        INGESTION_OUTPUT_DLQ_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_OVERFLOW_TOPIC: KAFKA_EVENTS_PLUGIN_INGESTION_OVERFLOW,
        INGESTION_OUTPUT_OVERFLOW_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_ASYNC_TOPIC: KAFKA_EVENTS_PLUGIN_INGESTION_ASYNC,
        INGESTION_OUTPUT_ASYNC_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_GROUPS_TOPIC: KAFKA_GROUPS,
        INGESTION_OUTPUT_GROUPS_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_PERSONS_TOPIC: KAFKA_PERSON,
        INGESTION_OUTPUT_PERSONS_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_PERSON_DISTINCT_IDS_TOPIC: KAFKA_PERSON_DISTINCT_ID,
        INGESTION_OUTPUT_PERSON_DISTINCT_IDS_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_APP_METRICS_TOPIC: KAFKA_APP_METRICS_2,
        INGESTION_OUTPUT_APP_METRICS_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_LOG_ENTRIES_TOPIC: KAFKA_LOG_ENTRIES,
        INGESTION_OUTPUT_LOG_ENTRIES_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_TOPHOG_TOPIC: KAFKA_CLICKHOUSE_TOPHOG,
        INGESTION_OUTPUT_TOPHOG_PRODUCER: DEFAULT_PRODUCER,
    }
}

/** Register all analytics ingestion outputs on the builder. Call `.build(registry, config)` to resolve. */
export function registerIngestionOutputs() {
    return new IngestionOutputsBuilder()
        .register(EVENTS_OUTPUT, {
            topicKey: 'INGESTION_OUTPUT_EVENTS_TOPIC',
            producerKey: 'INGESTION_OUTPUT_EVENTS_PRODUCER',
        })
        .register(AI_EVENTS_OUTPUT, {
            topicKey: 'INGESTION_OUTPUT_AI_EVENTS_TOPIC',
            producerKey: 'INGESTION_OUTPUT_AI_EVENTS_PRODUCER',
        })
        .register(HEATMAPS_OUTPUT, {
            topicKey: 'INGESTION_OUTPUT_HEATMAPS_TOPIC',
            producerKey: 'INGESTION_OUTPUT_HEATMAPS_PRODUCER',
        })
        .register(INGESTION_WARNINGS_OUTPUT, {
            topicKey: 'INGESTION_OUTPUT_INGESTION_WARNINGS_TOPIC',
            producerKey: 'INGESTION_OUTPUT_INGESTION_WARNINGS_PRODUCER',
        })
        .register(DLQ_OUTPUT, { topicKey: 'INGESTION_OUTPUT_DLQ_TOPIC', producerKey: 'INGESTION_OUTPUT_DLQ_PRODUCER' })
        .register(OVERFLOW_OUTPUT, {
            topicKey: 'INGESTION_OUTPUT_OVERFLOW_TOPIC',
            producerKey: 'INGESTION_OUTPUT_OVERFLOW_PRODUCER',
        })
        .register(ASYNC_OUTPUT, {
            topicKey: 'INGESTION_OUTPUT_ASYNC_TOPIC',
            producerKey: 'INGESTION_OUTPUT_ASYNC_PRODUCER',
        })
        .register(GROUPS_OUTPUT, {
            topicKey: 'INGESTION_OUTPUT_GROUPS_TOPIC',
            producerKey: 'INGESTION_OUTPUT_GROUPS_PRODUCER',
        })
        .register(PERSONS_OUTPUT, {
            topicKey: 'INGESTION_OUTPUT_PERSONS_TOPIC',
            producerKey: 'INGESTION_OUTPUT_PERSONS_PRODUCER',
        })
        .register(PERSON_DISTINCT_IDS_OUTPUT, {
            topicKey: 'INGESTION_OUTPUT_PERSON_DISTINCT_IDS_TOPIC',
            producerKey: 'INGESTION_OUTPUT_PERSON_DISTINCT_IDS_PRODUCER',
        })
        .register(APP_METRICS_OUTPUT, {
            topicKey: 'INGESTION_OUTPUT_APP_METRICS_TOPIC',
            producerKey: 'INGESTION_OUTPUT_APP_METRICS_PRODUCER',
        })
        .register(LOG_ENTRIES_OUTPUT, {
            topicKey: 'INGESTION_OUTPUT_LOG_ENTRIES_TOPIC',
            producerKey: 'INGESTION_OUTPUT_LOG_ENTRIES_PRODUCER',
        })
        .register(TOPHOG_OUTPUT, {
            topicKey: 'INGESTION_OUTPUT_TOPHOG_TOPIC',
            producerKey: 'INGESTION_OUTPUT_TOPHOG_PRODUCER',
        })
}
